### ISSUE TITLE
Develop the Upcoming Event section of the Event page (Figma Link Below)

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/Hacktoberfest2023-Ekiti#20]
https://www.figma.com/design/w1Hoj9ESFonR8tDl5WLedU/Event-Management?node-id=0-1&node-type=canvas&t=LaYd43Mtw6Tn6FYp-0

**Comment by nobledeveloper01** [comment]
Pls assign me to this

**Comment by ariyoaresa** [comment]
I'ld love towork on this

**Comment by OSCA-Ado-Ekiti** [comment]
assigned @nobledeveloper01
