### ISSUE TITLE
Import the Subscribe, Fotter section on the Event page and write the content atop the Subscribe (Figma Link Below)

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/Hacktoberfest2023-Ekiti#21]
https://www.figma.com/design/w1Hoj9ESFonR8tDl5WLedU/Event-Management?node-id=0-1&node-type=canvas&t=LaYd43Mtw6Tn6FYp-0

**Comment by Maloney18** [comment]
the info is quite foggy, but let me try this out. Assign me

**Comment by OSCA-Ado-Ekiti** [comment]
Assigned @Maloney18 
On the design there is a text content on the subscribe section after importing the Fotter and subscribe section, write the text content at the top of the subscribe

**Comment by Maloney18** [comment]
okay, I'll check it out
