### ISSUE TITLE
Develop the Previous Event section on the About us page (Figma link below) 

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/Hacktoberfest2023-Ekiti#25]
https://www.figma.com/design/w1Hoj9ESFonR8tDl5WLedU/Event-Management?node-id=0-1&node-type=canvas&t=LaYd43Mtw6Tn6FYp-0

**Comment by AnkitDev1505** [comment]
Previous Event section it also already exist

**Comment by nobledeveloper01** [comment]
Assign me to this, its not existing

**Comment by OSCA-Ado-Ekiti** [comment]
You can work on this @nobledeveloper01
