### ISSUE TITLE
Develop the Login Page

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/Hacktoberfest2023-Ekiti#27]
- https://www.figma.com/design/w1Hoj9ESFonR8tDl5WLedU/Event-Management?node-id=0-1&node-type=canvas&t=LaYd43Mtw6Tn6FYp-0)

**Comment by Maloney18** [comment]
Let me work on this

**Comment by OSCA-Ado-Ekiti** [comment]
You are in Hacktoberfest Ekiti community right

**Comment by OSCA-Ado-Ekiti** [comment]
Assigned✅

**Comment by nobledeveloper01** [comment]
we already have the login Page

**Comment by OSCA-Ado-Ekiti** [comment]
This as already been worked on
